---
- name: haproxy | install software-properties-common
  apt:
    name: software-properties-common
    state: present
  tags:
    - in_haproxy 

- name: Install lsb-release
  apt:
    name: lsb-release
  tags:
    - in_haproxy

- name: haproxy | install repo
  apt_repository:
    repo: 'ppa:vbernat/haproxy-1.9'
    codename: xenial

- name: Install packages initial
  apt: name={{ item }}  state=latest
  with_items:
    - haproxy 
  tags:
   - in_haproxy

- name: haproxy | copying haproxy.cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  tags:
    - in_haproxy
