---
- name: haproxy | setup systemd
  template:
    src: haproxy.service
    dest: /etc/systemd/system/haproxy.service
  notify:
    - restart haproxy
  tags:
    - haproxy  

- name: haproxy | copying haproxy.cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - reload haproxy
  tags:
    - haproxy

- name: haproxy | starting service
  systemd: name=haproxy state=started enabled=yes daemon_reload=yes
  tags:
    - haproxy

