### change from Ansible ###

pgsql_metrics:
  image: wrouesnel/postgres_exporter
  ports:
    - "9187:9187"
  environment:
    - "DATA_SOURCE_NAME=postgresql://postgres:{{ postgres_pass }}@{{ ansible_fqdn }}:5432/?sslmode=disable"
