---
- name: app node | rollback reset tag
  shell: git reset --hard {{ v_tag }}
  become: yes
  become_user: node
  args:
    chdir:  /home/node/{{ repo_desafio2 }}
  tags:
    - rollback

- name: app node | Install packages based on package.json.
  npm: path=/home/node/{{ repo_desafio2 }} state=present executable=/usr/local/node/bin/npm
  tags:
    - rollback


- name: app node | reload app
  command: su - node -c "/usr/local/node/bin/pm2 reload /home/node/{{ repo_desafio2 }}/pm2.json"
  tags:
    - rollback
