---

- name : app node | rollback
  command: su - node -c  "tar jxvf /home/node/backup/{{ repo_desafio2 }}-$(date +%Y-%m-%d).bz2 -C /home/node/{{ repo_desafio2 }}"
  tags:
    - rollback


- name: app node | Install packages based on package.json.
  npm: path=/home/node/{{ repo_desafio2 }} state=present executable=/usr/local/node/bin/npm
  tags:
    - rollback


- name: app node | reload app
  command: su - node -c "/usr/local/node/bin/pm2 reload /home/node/{{ repo_desafio2 }}/pm2.json"
  tags:
    - rollback
